#! /bin/bash
read Xenv < <(x11docker --xorg --gpu --display=9999 --xtest --no-auth --showenv nvidia-base-game-app-xorg-gl-unity xterm)
env $Xenv xpra start :9999 --use-display --start-via-proxy=no --daemon=no --bind-tcp=0.0.0.0:10000
